dist: bionic

os:
  - linux

services:
  - docker

branches:
  only:
    - develop
    - master
    - stable

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
    - DOCKER_COMPOSE_VERSION: 1.4.2

language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

matrix:
  fast_finish: true

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - sudo rm .env
  - echo "GIT_BRANCH=$TRAVIS_BRANCH" >> .env
  - echo "GIT_COMMIT_HASH=$COMMIT" >> .env
  - docker build --pull --force-rm --no-cache -f ./docker/nginx/Dockerfile -t "$REPO"/"$APP_NAME"_nginx:"$TRAVIS_BRANCH"-"$COMMIT" ./docker/nginx
  - docker build --pull --force-rm --no-cache -f ./Dockerfile -t "$REPO"/"$APP_NAME"_php:"$TRAVIS_BRANCH"-"$COMMIT" .

before_script:
  - travis_retry composer update -n
  - docker-compose up -d

script:
  # just a test script, literally.
  # needs to be executable, eg. $ chmod +x test.sh (locally)
  #   or you can chmod it in the before_install section above
  - sh ./test.sh

after_script:
  - docker-compose down

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$REPO"/"$APP_NAME"_nginx:"$TRAVIS_BRANCH"-"$COMMIT";
  - docker push "$REPO"/"$APP_NAME"_php:"$TRAVIS_BRANCH"-"$COMMIT";

sudo: required