version: '3'

services:
    nginx:
        # image: xx-array_nginx:latest
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - 443:443
            - 80:80
        depends_on:
            - php
        volumes:
            - /var/www/xx-array/:/var/www/xx-array
            - /var/www/xx-array/docker/nginx/certs/xx-array-cert.pem /etc/ssl/certs/xx-array-cert.pem
            - /var/www/xx-array/docker/nginx/certs/xx-array-key.pem /etc/ssl/private/xx-array-key.pem
            - /var/www/xx-array/docker/nginx/certs/dhparam.pem /etc/nginx/dhparam.pem
            - /var/www/xx-array/docker/nginx/conf/nginx.conf /etc/nginx/nginx.conf
            - /var/www/xx-array/docker/nginx/conf/xx-array.conf /etc/nginx/conf.d/xx-array.conf
            - /var/www/xx-array/docker/nginx/conf/self-signed.conf /etc/nginx/conf.d/self-signed.conf
            - /var/www/xx-array/docker/nginx/conf/ssl-params.conf /etc/nginx/conf.d/ssl-params.conf

    php:
        # image: xx-array_php:latest
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            TIMEZONE: America/Toronto
            APP_ENV: dev
        expose:
            - 9000
        deploy:
            mode: replicated
            replicas: 5
            restart_policy:
                condition: on-failure
        volumes:
            - /var/www/xx-array/:/var/www/xx-array