version: '3'

services:
    nginx:
        image: ${REPO}/${APP_NAME}_nginx:${BRANCH}-${COMMIT}
        depends_on:
            - php

    php:
        image: ${REPO}/${APP_NAME}_php:${BRANCH}-${COMMIT}