version: '3'

services:
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - 443:443
        depends_on:
            - php
        volumes:
            - ${APP_PATH}/:${APP_PATH}
            - ${APP_PATH}/docker/nginx/certs/${APP_NAME}-cert.pem /etc/ssl/certs/${APP_NAME}-cert.pem
            - ${APP_PATH}/docker/nginx/certs/${APP_NAME}-key.pem /etc/ssl/private/${APP_NAME}-key.pem
            - ${APP_PATH}/docker/nginx/certs/dhparam.pem /etc/nginx/dhparam.pem
            - ${APP_PATH}/docker/nginx/conf/nginx.conf /etc/nginx/nginx.conf
            - ${APP_PATH}/docker/nginx/conf/${APP_NAME}.conf /etc/nginx/conf.d/${APP_NAME}.conf
            - ${APP_PATH}/docker/nginx/conf/self-signed.conf /etc/nginx/conf.d/self-signed.conf
            - ${APP_PATH}/docker/nginx/conf/ssl-params.conf /etc/nginx/conf.d/ssl-params.conf

    php:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            TIMEZONE: America/Toronto
            APP_ENV: dev
        expose:
            - 9000
        deploy:
            mode: replicated
            replicas: 5
            restart_policy:
                condition: on-failure
        volumes:
            - ${APP_PATH}/:${APP_PATH}